export const loginSuccessPage = '/main/user'
export const loginSuccessMenu = '/main/user'
export const saveDataType = 'query'
export const baseURL = process.env.NODE_ENV === 'development' ? 'http://192.168.3.165:8555' : ''
export const publicPath = '/admin-v1'
export const serverErrorMsg = '服务器端出现错误，请联系管理员'
